### ISSUE TITLE
Page navigation not moving to final page

### ISSUE THREAD

**Issue by kdv24** [react-pdf-viewer/react-pdf-viewer#1388]
Since updating from react-pdf-viewer `3.7.0` to `3.10.0`, we are having issues with our page navigation not allowing us to go to the last page using the navigator. As you can see in the video below, there are 2248 pages in our pdf, but trying to go to the final page by using the arrows or by typing it into the page indicator only take the user to the second to last page. I can then scroll forward to the last page, but it still indicates it's the previous page.  Is it possible this is related to recent updates you've done @phuocng ?

https://user-images.githubusercontent.com/6107653/211102957-ccd9a7eb-e53f-4e6d-8f1d-161f9fd0e15d.mov

**Comment by phuocng** [comment]
Yes! I will fix it in the next version.

**Comment by phuocng** [comment]
Update: The issue is fixed in the latest code, and will be included in the next version!

https://user-images.githubusercontent.com/57786711/214736879-af314d3a-e50e-4fa1-86ce-ee4a2e9806e7.mp4

**Comment by phuocng** [comment]
Fixed in the [v3.11.0](https://react-pdf-viewer.dev/updates/).

**Comment by kdv24** [comment]
@phuocng we have updated to 3.11.0 but are still seeing the same issue.
