### ISSUE TITLE
Using fullscreen button when browser zoomed in causes infinite load

### ISSUE THREAD

**Issue by Bradley-developyn** [react-pdf-viewer/react-pdf-viewer#1559]
If you zoom your browser in to 110% then click the full screen button in the toolbar, you are presented with a infinite loading spinner.

**Comment by roviralinxea** [comment]
+1

**Comment by isimisi** [comment]
+1

**Comment by markkosorus** [comment]
+1

**Comment by souppower** [comment]
+1

**Comment by ColineVL** [comment]
I also have this problem

**Comment by souppower** [comment]
It seems like these lines are affecting the behaviors.
https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/packages/core/src/fullscreen/useFullScreen.ts#L171-L185

My assumption is this.
With a different zoom level, the if condition evaluates to falsey, and won't pass through the if statement. And it leads to the `setFullScreenMode(FullScreenMode.Entered);` statement not being called forever.

I tried to fix the problem by cloning this repo and building the source code, but it fails to build with some TypeScript and Rollup errors.

cc: @phuocng

**Comment by martijnpieters** [comment]
Apparently I made a duplicate ticket with #1714, but it sounds like it has been resolved for v4.0

**Comment by phuocng** [comment]
Yes, it's fixed in the latest implementation, and will be included in the upcoming v4.0.

**Comment by eckoSantoso** [comment]
i have same issue and waiting for v4.0.

However, if there is an immediate need, you can use this method as a temporary solution. Please note that this method does not resolve the issue permanently; it is only until the release of v4.

override loading area by css
`.rpv-full-screen__overlay {
            display: none;
        }`

**Comment by thekennysong** [comment]
@phuocng when will 4.0 be live?

**Comment by littlewhaleoo** [comment]
Another problem found after set disaplay none。
when i move the scrollbar，every page show loading and never show its content，only few pages content visible.
Do you guys have a workaround? 
@phuocng 
> i have same issue and waiting for v4.0.
> 
> However, if there is an immediate need, you can use this method as a temporary solution. Please note that this method does not resolve the issue permanently; it is only until the release of v4.
> 
> override loading area by css `.rpv-full-screen__overlay { display: none; }`

**Comment by boodigowda** [comment]
any permanent solution?

**Comment by shubham-pintar** [comment]
hi @phuocng  can you publish the latest version for 
https://www.npmjs.com/package/@react-pdf-viewer/core

as i see you have already merge the fix for 
"Using fullscreen button when browser zoomed in causes infinite load " but not pushed the latest verison. many users are facing the same issue. Please help
https://github.com/react-pdf-viewer/react-pdf-viewer/pull/1715
https://github.com/react-pdf-viewer/react-pdf-viewer/issues?q=state%3Aopen%20label%3A%22full-screen%20plugin%22

can you publish the latest version for 
https://www.npmjs.com/package/@react-pdf-viewer/core
