### ISSUE TITLE
TypeError: Cannot read property 'sendWithPromise' of null

### ISSUE THREAD

**Issue by dinesh-techahead** [react-pdf-viewer/react-pdf-viewer#417]
![screenshot-localhost_3001-2021 01 08-17_51_43](https://user-images.githubusercontent.com/74606207/104015146-3a6eea80-51da-11eb-9804-e088517c9f07.png)

**Comment by dinesh-techahead** [comment]
sometimes getting this error

**Comment by phuoc-ng** [comment]
Please give me the steps to reproduce the issue.

**Comment by dinesh-techahead** [comment]
I have multiple pdfs. i am switching between pdfs by pressing "next" and "prev" button

**Comment by phuoc-ng** [comment]
Can you create a sample project from one of [starter](https://github.com/react-pdf-viewer/starter)?

**Comment by ImDR** [comment]
hi @phuoc-ng,

this is the demo. https://github.com/ImDR/demo-pdf. 

when i am switching between pdfs sometime these errors are coming

**Comment by ImDR** [comment]
![screenshot-localhost_3000-2021 01 09-06_41_28](https://user-images.githubusercontent.com/16467335/104078918-85bee280-5246-11eb-8645-4d8c6aa55777.png)

**Comment by phuoc-ng** [comment]
@ImDR Great. I'll take a look at the repos you gave me.

**Comment by phuoc-ng** [comment]
I can confirm that now I can reproduce the issue:

<img width="749" alt="Screen Shot 2021-01-11 at 22 37 17" src="https://user-images.githubusercontent.com/57786711/104204966-6b605100-5460-11eb-8a3c-caf4bdec88e4.png">

**Comment by phuoc-ng** [comment]
@ImDR @dinesh-techahead 
This issue is fixed in #424. I'll include the fix in v2.3.2!

**Comment by phuoc-ng** [comment]
@ImDR @dinesh-techahead 
Please upgrade to [v2.3.2](https://react-pdf-viewer.dev/updates) which fixes the issue.

**Comment by venkatesh-soulpage** [comment]
![pdfviewer-error](https://user-images.githubusercontent.com/58929799/108848893-8c8f9200-7607-11eb-8166-9b052075e3ca.png)
Issue still raises even upgraded to 2.4.0 when trying to update file_url on every button clicks

**Comment by phuoc-ng** [comment]
@venkatesh-soulpage Please create a sample repository, so I can try/reproduce it.
However, I tried to remove the changes fixing the issue, and I'll see the issue

<img width="630" alt="Screen Shot 2021-02-26 at 16 44 12" src="https://user-images.githubusercontent.com/57786711/109414770-39428880-79e7-11eb-8aee-4065698e443e.png">

Adding the changes then the issue is gone.

The demo is quite simple as following

```js
import * as React from 'react';
import { PrimaryButton, SpecialZoomLevel, Viewer, Worker } from '@react-pdf-viewer/core';
import { defaultLayoutPlugin } from '@react-pdf-viewer/default-layout';
import { Zoom } from '@react-pdf-viewer/full-screen';
import { OnHighlightKeyword } from '@react-pdf-viewer/search';

import '@react-pdf-viewer/core/lib/styles/index.css';
import '@react-pdf-viewer/default-layout/lib/styles/index.css';

const SAMPLE_DOCS = [
    'sample-1.pdf',
    'sample-2.pdf',
    'sample-3.pdf',
    'sample-4.pdf',
];

const App = () => {
    const [index, setIndex] = React.useState(0);

    const defaultLayoutPluginInstance = defaultLayoutPlugin();
    const showPreviousDoc = () => {
        index > 0 && setIndex(index - 1);
    };
    const showNextDoc = () => {
        index < SAMPLE_DOCS.length - 1 && setIndex(index + 1);
    };

    return (
        <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.js">
            <div
                style={{
                    display: 'flex',
                    marginBottom: '16px',
                }}
            >
                <div style={{ marginRight: '8px' }}>
                    <PrimaryButton
                        onClick={showPreviousDoc}
                    >
                        Previous
                    </PrimaryButton>
                </div>
                <div style={{ marginRight: '8px' }}>
                    <PrimaryButton
                        onClick={showNextDoc}
                    >
                        Next
                    </PrimaryButton>
                </div>
            </div>
            <div
                style={{
                    height: '720px',
                    width: '640px',
                }}
            >
                <Viewer
                    fileUrl={`http://localhost:8001/${SAMPLE_DOCS[index]}`}
                    plugins={[
                        defaultLayoutPluginInstance,
                    ]}
                />
            </div>
        </Worker>
    );
};

export default App;
```

So, you can try it again by 
- removing your `node_modules/@react-pdf-viewer`, 
- making sure all `@react-pdf-viewer` packages in the `package.json` are `2.4.0`.
- reinstalling packages

**Comment by helderdias15** [comment]
Hello, i got this same issue when i'm concating different pages from different files
if the pdf Proxy its the same, there is no problems, but when i have multiples pdf proxys it will only render the last page
Im using Angular instead, with ng2-pdf-viewer version 7.0.1
the erros are exactly the same, can someone help me please?

**Comment by helderdias15** [comment]
![image](https://user-images.githubusercontent.com/61152845/134894343-6dae9cc2-62e5-48e0-890e-8607bd1719a5.png)

**Comment by phuoc-ng** [comment]
@helderdias15 It's interesting. Can you fork this [project](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut) and give me the steps to reproduce the issue?

**Comment by pedroferreira37** [comment]
Just add useAsync or your own implementation when generating the url, the @ldiqual response from #974 it ts what happens
