### ISSUE TITLE
defaultScale={SpecialZoomLevel.PageWidth} sometimes does not render the Viewer

### ISSUE THREAD

**Issue by JoostDeCupere** [react-pdf-viewer/react-pdf-viewer#884]
Using react-pdf-viewer with the following setup:
React-pdf-viewer (2.11.0)
Node: v14.17.5
npm: 8.1.0

Using the react-pdf-viewer with defaultScale={SpecialZoomLevel.PageWidth} set and a fileURL bound to a prop which can change on user click we have issues that sometimes (30% of the time) the pdf viewer displays a white canvas.
As this only happens now and then it feels like some sort of racing condition though this is just speculation.

The viewer gets eventually drawn on some triggers like 

- when you hover over it and scroll
- Resizing the parent container
- When you inspect the parent element (litterally going in the dev tools and hovering over the parent element draws it)

**Comment by phuoc-ng** [comment]
Is it possible to reproduce the issue? (you can fork this [sample project](https://codesandbox.io/s/react-pdf-viewer-forked-yc8ut))

**Comment by JoostDeCupere** [comment]
Hi, sorry for the delay, lost track of this.
I reproduced the issue in this forked project.
https://codesandbox.io/s/react-pdf-viewer-sample-joost-xmlqr

Please notice it only seems to happen when the fileUrl is changed. (hence I added a button to do so).
I also dont seem to have the issue with the defaultlayout plugin.

Here is a video for your convenience that also displays it: https://drive.google.com/file/d/1J4SbvfvpDfOih4hmFtTX7R9ZnGEz6GaR/view?usp=sharing

**Comment by phuoc-ng** [comment]
@JoostDeCupere 
Thanks a lot for getting back to me!

I fixed and added some test cases for switching between documents. The issue should be fixed in [v3.0.0](https://react-pdf-viewer.dev/updates/) which was released.

Here is the updated project that runs the latest v3.0.0:
https://codesandbox.io/s/react-pdf-viewer-sample-joost-forked-b72c1

Can you give it a try?

**Comment by JoostDeCupere** [comment]
Hi,

Once again sorry for the delay.
Thanks for coming up with a fix.
Unfortunatly the fix does not seem to solve the issue completly yet.
looking at the updated project https://codesandbox.io/s/react-pdf-viewer-sample-joost-forked-b72c1?file=/package.json the viewer still shows a white pdf untill you hover over it.
Here is a video showing the issue: https://drive.google.com/file/d/1Mgmqu5d8U2k5ddZOND3xwzQbie8-l7rd/view?usp=sharing

Kind regards,
Joost

**Comment by thevipulsharma** [comment]
Hi,

I am facing this same issue. I tried https://codesandbox.io/s/react-pdf-viewer-sample-joost-forked-b72c1?file=/package.json in Firefox and Chrome browsers, and it seems the issue only appears in Chrome browser.

**Comment by qwertyvipul** [comment]
Hi @phuoc-ng, 

Any update on https://github.com/react-pdf-viewer/react-pdf-viewer/issues/884#issuecomment-1033490602?

**Comment by qwertyvipul** [comment]
For me. the issue got fixed in the latest version - https://github.com/react-pdf-viewer/react-pdf-viewer/issues/1010#issuecomment-1056961441

**Comment by JoostDeCupere** [comment]
3.1.1 fixes the issue indeed. Closing this ticket
