### ISSUE TITLE
Pages do not load when zoom level is set to page width

### ISSUE THREAD

**Issue by sirkrisp** [react-pdf-viewer/react-pdf-viewer#990]
There seems to be a weird buck when zoom level = page width

I recorded a video to demonstrate it: https://www.youtube.com/watch?v=gz6cHfvjRVg

**Comment by phuoc-ng** [comment]
Fixed in the latest code, and will be included in the next release.

**Comment by phuoc-ng** [comment]
Fixed in [v3.2.0](https://react-pdf-viewer.dev/updates/). Please upgrade.

**Comment by sirkrisp** [comment]
Hi, thanks for the update! For some reason, in my App pages still do not render sometimes if I set width to page width, or, pages are rendered only on some zoom levels. I use a custom page renderer:

```typescript
export function PageRenderer({renderPageProps}: {
    renderPageProps: RenderPageProps,
}) {
    const isInAddMode = useSelector((state: RootState) => state.pdfViewer.inAddMode)

    useEffect(() => {
        if (renderPageProps.canvasLayerRendered && renderPageProps.textLayerRendered) {
            renderPageProps.markRendered(renderPageProps.pageIndex);
        }
    }, [renderPageProps]);

    return (
        <div
            style={{
                width: "100%",
                height: "100%",
                position: "relative"
            }}
            onClick={(e) => {
                const target = e.currentTarget
                if (target instanceof HTMLElement) {
                    const pageRect = target.getBoundingClientRect()
                    const top = (e.clientY - pageRect.top) / pageRect.height * 100;
                    const left = (e.clientX - pageRect.left) / pageRect.width * 100;
                    pdfViewerEventManager._emit("mouseClickInPage", {
                        pagePosition: {
                            top,
                            left
                        },
                        pageIndex: renderPageProps.pageIndex
                    })
                }
            }}
            onMouseEnter={() => {
                pdfViewerEventManager._emit("mouseEntersPage", {
                    pageIndex: renderPageProps.pageIndex
                })
            }}
            onMouseLeave={() => {
                pdfViewerEventManager._emit("mouseLeavesPage", {
                    pageIndex: renderPageProps.pageIndex
                })
            }}
        >
            {
                isInAddMode &&
                <div style={{
                    position: "absolute",
                    width: "100%",
                    height: "100%",
                    cursor: "none",
                    zIndex: 2,
                    left: "0%",
                    top: "0%"
                }}/>
            }
            {renderPageProps.canvasLayer.children}
            {renderPageProps.textLayer.children}
            {renderPageProps.annotationLayer.children}
        </div>
    )
}
```

Moreover, I also use custom CSS to render the page:

```css
.rpv-core__page-layer{
  box-shadow: none !important;
}

.rpv-core__annotation-layer {
  -webkit-animation: fadein 2s; /* Safari, Chrome and Opera > 12.1 */
  -moz-animation: fadein 2s; /* Firefox < 16 */
  -ms-animation: fadein 2s; /* Internet Explorer */
  -o-animation: fadein 2s; /* Opera < 12.1 */
  animation: fadein 2s;
}

.rpv-core__canvas-layer{
  -webkit-animation: fadein 2s; /* Safari, Chrome and Opera > 12.1 */
  -moz-animation: fadein 2s; /* Firefox < 16 */
  -ms-animation: fadein 2s; /* Internet Explorer */
  -o-animation: fadein 2s; /* Opera < 12.1 */
  animation: fadein 2s;
}

.rpv-core__inner-page{
  background-color: #E5E7E9 !important;
  box-sizing: border-box !important;
}

.rpv-core__spinner {
  visibility: hidden !important;
}

.rpv-core__inner-pages {
  background-color: #E5E7E9 !important;
}

.rpv-core__viewer {
  background-color: #E5E7E9 !important;
}
```

Do you have some tips to why pages do not render?

**Comment by sirkrisp** [comment]
Hi, I just noticed that when I use the following it works!

```typescript
useEffect(() => {
        if (renderPageProps.textLayerRendered) {
            renderPageProps.markRendered(renderPageProps.pageIndex);
        }
    }, [renderPageProps.textLayerRendered]);
```

From here https://react-pdf-viewer.dev/examples/replace-the-canvas-with-svg-layer/

**Comment by sirkrisp** [comment]
I just tested a bit more and some pages still do not render when resizing the window, at least in my app (although it is now much better than before).
